export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Header } from '@/components/Navbar'
import { Roboto } from "next/font/google"; 
import '@/app/ui/global.css';

const roboto = Roboto({ weight: ['400', '700'], subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        <main className="py-20 max-w-6xl mx-auto">
          {children}
        </main>
      </body>
    </html>
  )
}
